Repository discreetlogcontracts/dlcspecs, pull requests merged in 2021-11, with the labels that each got.

#179 Fix numeric outcome rounding interval link
  NumericOutcome.md
Labels: bug

#178 Tuesday November 9 2021 Meeting
  meeting/meeting_november_9_2021.md
Labels: meeting

#154 Adaptor point optimizations
  NumericOutcomeCompression.md
Labels: enhancement, cet, adaptor-sigs
