Repository discreetlogcontracts/dlcspecs, pull requests merged in 2022-06, with the labels that each got.

#195 Tuesday May 10 2022 Meeting
  meeting/meeting_may_10_2022.md
Labels: meeting

#163 Update messaging and serialization
  Messaging.md
  NumericOutcome.md
  PayoutCurve.md
  Protocol.md
  test/test_vectors/enum_3_of_3_test.json
  test/test_vectors/enum_3_of_5_test.json
  test/test_vectors/enum_and_numerical_3_of_5_test.json
  test/test_vectors/enum_and_numerical_5_of_5_test.json
  test/test_vectors/enum_and_numerical_with_diff_3_of_5_test.json
  test/test_vectors/enum_and_numerical_with_diff_5_of_5_test.json
  test/test_vectors/enum_single_oracle_test.json
  test/test_vectors/single_oracle_numerical_hyperbola_test.json
  test/test_vectors/single_oracle_numerical_test.json
  test/test_vectors/three_of_five_oracle_numerical_with_diff_test.json
  test/test_vectors/three_of_three_oracle_numerical_test.json
  test/test_vectors/three_of_three_oracle_numerical_with_diff_test.json
  test/test_vectors/two_of_five_oracle_numerical_test.json
  test/test_vectors/two_of_five_oracle_numerical_with_diff_test.json
Labels: breaking, needs 2 impl

#188 Add test vector for contract id computation
  Protocol.md
  test/contract_id_test.json
Labels: needs 2 impl
